language: ruby
sudo: false
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
script:
  - bundle exec rake db:setup test
env:
  - RAILS_VERSION=4.0.0
  - RAILS_VERSION=4.1.0
  - RAILS_VERSION=4.2.0
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - rbx
  - jruby
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx
    - rvm: jruby
